# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/playground',
                'doc_host': 'https://xiaochuany.github.io',
                'git_url': 'https://github.com/xiaochuany/playground',
                'lib_path': 'playground'},
  'syms': {'playground.core': {'playground.core.foo': ('core.html#foo', 'playground/core.py')}}}
